# Application Vocabulary and Translations

LANGUAGES = {
    "en": {
        "title": "MapleStory Boss DPM Monitor",
        "config_frame": " Configuration ",
        "dashboard_frame": " Combat Data Dashboard ",
        "window_list_label": "Target Window:",
        "refresh_btn": "Refresh Window List",
        "set_region_btn": "Set Capture Region (Crop)",
        "region_not_set": "REGION NOT SET",
        "region_set": "REGION CUSTOM SET",
        "freq_label": "Freq (Hz):",
        "hotkey_hint": "F7: Toggle Monitoring  |  F8: Reset  |  F9: Show/Hide HUD",
        "hp_label": "Remaining HP",
        "rt_dps_label": "Real-time DPS",
        "rt_dpm_label": "Real-time DPM",
        "combat_time_label": "Combat Time",
        "rem_time_label": "Remaining Time",
        "total_dmg_label": "Total Damage",
        "avg_dpm_label": "Average DPM",
        "gen_report_btn": "GENERATE REPORT (.PNG)",
        "export_csv_btn": "EXPORT RAW DATA (.CSV)",
        "engine_ready": "Engine: Ready",
        "engine_loading": "Engine: Loading...",
        "status_idle": "IDLE",
        "status_ready": "READY",
        "status_active": "ACTIVE",
        "status_paused": "PAUSED",
        "status_finished": "FINISHED",
        "monitoring_on": "Monitoring: ON",
        "monitoring_off": "Monitoring: OFF",
        "hw_label": "HW:",
        "report_title": "BOSS DPS/DPM Analysis",
        "report_xlabel": "Combat Duration (Seconds)",
        "report_ylabel": "Damage Per Second (DPS)",
        "avg_dps_legend": "Average DPS",
        "success_msg": "Success",
        "report_saved": "Report saved:",
        "csv_exported": "Raw data exported:",
        "warning_msg": "Warning",
        "no_data_msg": "No combat data to report.",
        "not_enough_data": "Not enough data points for a smooth report.",
        "hud_combat_time": "COMBAT TIME",
        "hud_rt_dps": "REAL-TIME DPS",
        "hud_total_dmg": "TOTAL DAMAGE",
        "hud_remaining": "REMAINING",
        "hud_avg_dpm": "AVERAGE DPM",
        "hud_status": "STATUS",
    },
    "zh": {
        "title": "楓之谷 Boss DPM 監控工具",
        "config_frame": " 設定 ",
        "dashboard_frame": " 戰鬥數據面板 ",
        "window_list_label": "目標視窗:",
        "refresh_btn": "重新整理視窗列表",
        "set_region_btn": "設定截取區域 (裁剪)",
        "region_not_set": "尚未設定區域",
        "region_set": "自定義區域已設定",
        "freq_label": "偵測頻率 (Hz):",
        "hotkey_hint": "F7: 開啟/停止監控  |  F8: 重設  |  F9: 顯示/隱藏 HUD",
        "hp_label": "剩餘血量",
        "rt_dps_label": "即時 DPS",
        "rt_dpm_label": "即時 DPM",
        "combat_time_label": "戰鬥時間",
        "rem_time_label": "剩餘時間",
        "total_dmg_label": "累積傷害",
        "avg_dpm_label": "平均 DPM",
        "gen_report_btn": "生成分析報告 (.PNG)",
        "export_csv_btn": "匯出原始數據 (.CSV)",
        "engine_ready": "引擎狀態: 就緒",
        "engine_loading": "引擎狀態: 載入中...",
        "status_idle": "待機",
        "status_ready": "準備中",
        "status_active": "戰鬥中",
        "status_paused": "已暫停",
        "status_finished": "戰鬥結束",
        "monitoring_on": "監控狀態: 開啟",
        "monitoring_off": "監控狀態: 關閉",
        "hw_label": "硬體:",
        "report_title": "BOSS DPS/DPM 戰鬥數據分析",
        "report_xlabel": "戰鬥時長 (秒)",
        "report_ylabel": "每秒傷害 (DPS)",
        "avg_dps_legend": "平均 DPS",
        "success_msg": "成功",
        "report_saved": "報告已儲存:",
        "csv_exported": "原始數據已匯出:",
        "warning_msg": "警告",
        "no_data_msg": "無戰鬥數據可供報告。",
        "not_enough_data": "數據點不足，無法生成平滑報告。",
        "hud_combat_time": "戰鬥時間",
        "hud_rt_dps": "即時 DPS",
        "hud_total_dmg": "累積傷害",
        "hud_remaining": "預估剩餘時間",
        "hud_avg_dpm": "平均 DPM",
        "hud_status": "狀態",
    },
}
